### ISSUE TITLE
Can I base64 encoding the File(Blob)?

### ISSUE THREAD

**Issue by devGW** [dankogai/js-base64#105]
## Description
can anyone tell me how to encode a File as base64?

[
![스크린샷 2020-05-21 오후 8 51 35](https://user-images.githubusercontent.com/39829378/82556554-ee1c5f00-9ba4-11ea-9faa-6c46b0684bf7.png)
](url)

**Comment by kota-yata** [comment]
Your code should work properly if your `fileList` is really a single Blob file. Blob is available for the argument of `Base64.encode`.

Basic blob example is like so:
```html
<input type="file" onchange="fileChange()" id="file"/>
```
```js
const fileChange = () => {
  const target = document.getElementById('file'); // HTMLInputElement
  const file = target.files[0]; // blob
  const encoded = Base64.encode(file);
};
```

Check the docs carefully in case you've kept this problem unsolved for over a year.

**Comment by wzh19940000** [comment]
我能将一个网络图片转成base64格式么？或者一个本地图片路径转成base64格式，例如这种
![image](https://user-images.githubusercontent.com/20918643/133086095-a9e65e63-4017-4325-999f-6b93ed98fafb.png)

**Comment by kota-yata** [comment]
You can just use fetch
```js
const test = async () => {
  const blob = await fetch("https://sample.com/yourimage.png");
  const res = await blob.blob();
  return res;
}
```
This test function will return blob file of the image. And now you can use ```Base64.encode()``` as I explained above.

**Comment by dankogai** [comment]
A slightly more descriptive example:

```javascript
const fetchBase64 = async (url) => {
    const res = await fetch(url);
    if (res.ok) {
        const buf = await res.arrayBuffer();
        return Base64.fromUint8Array(new Uint8Array(buf));
    } else {
        return Promise.reject(res);
    }
}

fetchBase64('https://www.dan.co.jp/favicon.png')
    .then(console.log)
    .catch(console.error);
```

**Comment by EskelCz** [comment]
> ```js
>   const encoded = Base64.encode(file);
> ```
When I try this I get `W29iamVjdCBGaWxlXQ==`, which is `[object File]`
[Demo](https://jsfiddle.net/ojcgL8em/)

**Comment by EskelCz** [comment]
It works from the ArrayBuffer (second example)
[Demo](https://jsfiddle.net/bko8vhsq/)
