### ISSUE TITLE
Any method that provides URL and Filename safe type base64 encoding scheme.

### ISSUE THREAD

**Issue by SethiShivam** [dankogai/js-base64#107]
Hi Team,
I am trying to find out some alternate method for base64.urlsafe_b64decode(available in python library)
I am actually looking for file and URL safe encoding and decoding scheme.

Could you please tell which method shall I use to achieve this?

Best Regards
Sethi Shivam

**Comment by dankogai** [comment]
`Base64.decode()` decodes both flavors of Base64 as [SYNOPSIS] says.  Maybe I should add `.decodeURI()` as an alias of `.decode()`…

[SYNOPSIS]: https://github.com/dankogai/js-base64/blob/master/README.md#synopsis

**Comment by SethiShivam** [comment]
Hi dankogai , Thanks for the response. 
I am looking for the encoding method as well so that I can encode and decode both for URL safe.

Best Regards
Sethi Shivam

**Comment by dankogai** [comment]
`Base64.encodeURI()` is exactly what you are looking for.

**Comment by SethiShivam** [comment]
Yes .... shall I use the existing encode method ?  or the functionality doesn't exist yet ?

**Comment by dankogai** [comment]
READ [SYNOPIS] NOT JUST THREAD!  THE FUNCTIONALITY ALREADY EXISTS!

[SYNOPSIS]: https://github.com/dankogai/js-base64/blob/master/README.md#synopsis

```javascript
Base64.encode('小飼弾');    // 5bCP6aO85by+
Base64.encodeURI('小飼弾'); // 5bCP6aO85by-
Base64.decode('5bCP6aO85by+');  // 小飼弾
// note .decodeURI() is unnecessary since it accepts both flavors
Base64.decode('5bCP6aO85by-');  // 小飼弾
```

case dismissed.
