### ISSUE TITLE
Missing base64.min.js

### ISSUE THREAD

**Issue by Twixy69** [dankogai/js-base64#111]
Hi,

I recently created a new VM for our intern. After hit 'npm i' on our project then launched cypress we got the terrible error saying that base64.min.js is now missing.

And yes, this file is not anymore in our node-modules/js-base64 folder. After some research, it appears that you deleted the file from your repo. Can you add it again ?

We fixed this trouble by copying base-64.min.js from your old commit. Any other idea to solve this 2nd degree dependance ?

Thank you very much. 

Laurent C.

**Comment by dankogai** [comment]
No I can't and won't.  I have removed it because js minification should be done by users.

https://github.com/mishoo/UglifyJS

Some CDNs even do it automatically, e.g:

https://cdn.jsdelivr.net/npm/js-base64/base64.min.js

**Comment by Twixy69** [comment]
Ok thank you for fast response !

**Comment by dankogai** [comment]
https://github.com/dankogai/js-base64/issues/113#issuecomment-667818207
