### ISSUE TITLE
URI safe encoded Uint8Array cannot be decoded

### ISSUE THREAD

**Issue by polarstoat** [dankogai/js-base64#112]
Using `Base64.fromUint8Array(new Uint8Array([0x00, 0x00, 0x3F]), true);` returns `"AAA_"`, a URI safe encode.

But when decoding that with `Base64.toUint8Array("AAA_");` we get `Uint8Array <00, 00>`; the URI safe 63rd character (`_`) has been ignored.

Using `Base64.toUint8Array("AAA/");` gives the expected result of `Uint8Array <00, 00, 3F>`.

I can confirm this also occurs when trying to decode strings including the URI safe 62nd character (`-`).

See [this RunKit code](https://runkit.com/embed/23u97s1raev6) (also below) for an example of the issue.

```js
const Base64 = require('js-base64').Base64;

const byteArray = new Uint8Array([0x00, 0x00, 0x3F]);

console.log(Base64.fromUint8Array(byteArray)); // "AAA/"
console.log(Base64.fromUint8Array(byteArray, true)); // "AAA_"

console.log(Base64.toUint8Array("AAA/")); // Uint8Array <00, 00, 3F>

console.log(Base64.toUint8Array("AAA_")); // Uint8Array <00, 00>
```

**Comment by dankogai** [comment]
Thank you.  fixed in b70bf7ec3117cd68967927dcb851a994349f9357 .
