### ISSUE TITLE
Removal of minified version is a major version update, not minor

### ISSUE THREAD

**Issue by kirill-konshin** [dankogai/js-base64#113]
Either put back the `base64.min.js` file or bump the major version, as some other packages may also depend on it: https://github.com/meinaart/cypress-plugin-snapshots/issues/136

**Comment by dankogai** [comment]
No I won't.  JS minification should be done by user side.

cf. https://github.com/dankogai/js-base64/issues/111

As mentioned there there are even CDNs that does that for you.

**Comment by kirill-konshin** [comment]
@dankogai even if this is true, you've changed the public API of the package, which is a major version bump according to semver.

**Comment by dankogai** [comment]
Minified version is NOT A PART OF THE API, PERIOD.

**Comment by kirill-konshin** [comment]
@dankogai you may deny it, but once it was published it became a part of public API, even if it was not your intent. You can't take it back like you did :)

P.S. I am trying to help, stop yelling please. This is counter productive.

**Comment by dankogai** [comment]
No it is not.  Just because it was there in the distro it does not automatically make it an API.  Suppose you accidentally included a `.o` or `.so` or `.dylib` in your C/C++ project repo, does that make it an API?  Are files under `test/` part of the API?

I am not yelling.  I was wrong to have included `.min.js` and your "help" is another proof it was wrong.

**Comment by kirill-konshin** [comment]
> Just because it was there in the distro it does not automatically make it an API

It kinda does in JS world. Especially in regards with `.min` files. People assume it's official minified version and begin using it, and the evidence of such behavior is quite clear.

> Suppose you accidentally included a .o or .so or .dylib in your C/C++ project repo

Well then you need to deprecate the version or even unpublish it, if something has leaked unintentionally. But something tells me you intentionally included the minified version...

I don't mind if you remove it, it's a right choice after all, but you can't remove it the way you did, that's my point. Once it's there — it's there, until next major version. This is the core principle behind semver. Since your package is popular and is widely used, you have to be very careful with this.

**Comment by lucaspottersky** [comment]
@dankogai hey man, i see you have strong opinions about that. But please, take some time to reconsider what @kirill-konshin is presenting here.

anyways, thanks for this great lib and all the effort you whole heartedly put onto it!

**Comment by dankogai** [comment]
I just released [2.6.4] with `base64.min.js` under [version2] branch, which will be the final version for the branch.  Version 3 and on will not have `.min.js` in the repo, period.

[2.6.4]: https://github.com/dankogai/js-base64/tree/2.6.4
[version2]: https://github.com/dankogai/js-base64/tree/version2

Case closed.
