### ISSUE TITLE
feature request: native ES module support

### ISSUE THREAD

**Issue by JounQin** [dankogai/js-base64#114]

**Comment by dankogai** [comment]
You've got it! 0d9d81cfc1a125fcf642066412f5bc41dbcdb75f

As a matter of fact, `base64.js` is now auto-generated from `base64.mjs`!

**Comment by JounQin** [comment]
I have to say that the code in `base64.mjs` is not tree shakable actually.
It would be nicer to support tree shaking.

**Comment by dankogai** [comment]
Honestly I was not familiar w/ the term "tree shaking".

* https://en.wikipedia.org/wiki/Tree_shaking

Okay, I see.  Well, I think `js-base64` is too small a module for tree-shakability to become an issue.
* the whole thing fits nicely in a single object which acts as a namespace (`Base64` or whatever you (re)name it).
* `js-base64` has no dependency except for JS runtime.

However, It is generally nice to be more tree shakable.  If you have an idea or suggestion please let me know.  PR is even more welcome.

**Comment by JounQin** [comment]
OK, I'd like to raise a PR in recent days.
