### ISSUE TITLE
`global` should not be modified in commonjs format

### ISSUE THREAD

**Issue by iManoir** [dankogai/js-base64#119]
First thanks for writing this module, but I find it will always add `Base64` into `global` value, it could be unexpected behavior.

I know I can do `Base64. noConflict()`, but `'Base64' in global === true`, and this step is bad as I see.

Or it should only be added automatically if `module` and `define` unavailable.

**Comment by dankogai** [comment]
You are right.  `global` is modified for the sake of the oldest loading method, `<script src=`.  864d2ed73b655a5f293b9b2b18f44ce5f40da4d6 addresses this problem modifying `global` iff  neither `module` nor `define` is present.

**Comment by iManoir** [comment]
Thanks for your quick fix! After reading the code, the check of `module/define/global` seems be called twice which is actually redundant.

I'm raising another PR to simplify the codes at https://github.com/dankogai/js-base64/pull/120!

**Comment by 1937871222gh** [comment]
不支持ie
