### ISSUE TITLE
this js can not run in IE 11 browser?

### ISSUE THREAD

**Issue by Cherry-Ran** [dankogai/js-base64#127]
this js can not run in IE 11 browser?

**Comment by Cherry-Ran** [comment]
pleaselook this website http://www.voidcn.com/code/p-qfnepmhx-p.html   i  import this js in HTML
 and then 
Base64.encode(data.field.loginName);
Base64.encode(data.field.password);

run application and the IE 11 browser console "base64 is not defined"

**Comment by dankogai** [comment]
IE 11 support is dropped from version 3.  Use version 2.x or `make base64.es5.js` in the cloned repository directory.

**Comment by Cherry-Ran** [comment]
> IE 11 support is dropped from version 3. Use version 2.x or `make base64.es5.js` in the cloned repository directory.

OK,thanks very much!
