### ISSUE TITLE
U8s input and output are inconsistent

### ISSUE THREAD

**Issue by LskGame** [dankogai/js-base64#128]
let u8s = new Uint8Array([96,-28,-67,-96,-27,-91,-67]);
undefined
Base64.fromUint8Array(u8s);
"YOS9oOWlvQ=="
Base64.toUint8Array("YOS9oOWlvQ==");
Uint8Array(7) [96, 228, 189, 160, 229, 165, 189]

**Comment by dankogai** [comment]
No. inconsistent is you feeding NEGATIVE VALUE.
`Uint8Array` stands for `An array of UInt8`.
Uint8 stands for UNSIGNED 8bit integer.
**UNSIGNED**.
<img width="395" alt="console" src="https://user-images.githubusercontent.com/68812/91385079-0d451f80-e86b-11ea-875a-aa817c4c2985.png">
