### ISSUE TITLE
Character ă cannot btoa

### ISSUE THREAD

**Issue by xxstop** [dankogai/js-base64#131]
Character ă cannot btoa

Error:
```
Uncaught DOMException: Failed to execute 'btoa' on 'Window': The string to be encoded contains characters outside of the Latin1 range.
```

**Comment by dankogai** [comment]
`btoa` only accepts `\x00` to `\xff` but `'ă'.charCodeAt(0) === 259  === 0x103 > 0xFF`.  It is a feature.

https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/btoa
