### ISSUE TITLE
Add isBase64( ) function

### ISSUE THREAD

**Issue by evaliyev** [dankogai/js-base64#132]
It would be nice to have a function to test if a string is a valid encoded base64 string

**Comment by dankogai** [comment]
As in my response to https://github.com/dankogai/js-base64/issues/80

```
value.match(/^[0-9a-zA-Z+\/]+[=]{0,3}$/);
```

Should do.  But I have several similar requests so I decided to add it.

**Comment by dankogai** [comment]
Added `.isValid()` that does this.

https://github.com/dankogai/js-base64/commit/ad8897c84bf6b2607a718fbf390ddde63cb4ceff
