### ISSUE TITLE
IE Suport

### ISSUE THREAD

**Issue by GuoSirius** [dankogai/js-base64#134]
arrow function and spread operator need transform

![image](https://user-images.githubusercontent.com/48358523/103970261-c5cc8980-51a2-11eb-9853-c76eebe10640.png)

**Comment by dankogai** [comment]
It is explicitly documented in [README.md].  Use [Version 2] or transpile` base64.ts` yourself 

[README.md]: https://github.com/dankogai/js-base64#heads-up
[Version 2]: https://github.com/dankogai/js-base64/tree/version2
