### ISSUE TITLE
Uint8Array.from failed to work in some safari version

### ISSUE THREAD

**Issue by g1f9** [dankogai/js-base64#137]
System：mac 10.15.6 
Safari Version: 13.1.2 

![image](https://user-images.githubusercontent.com/32266694/104145290-57393700-5401-11eb-8a44-ed5b59826c10.png)

**Comment by dankogai** [comment]
I need more information.  FYI it is tested on Safari, too.   What happens when you open [test/index.html] with it?

[test/index.html]: https://github.com/dankogai/js-base64/blob/main/test/index.html

**Comment by miaozi1123** [comment]
I has the same problems,when i run in ios wkwebview,it's can not decode UTF-8,but when i choose to 1.25.1,It's ok

**Comment by amirbardugo** [comment]
happens to me too, safari 13.1.3,  any update @dankogai

**Comment by dankogai** [comment]
I cannot reproduce your claim.  Please try the following. here we assume you already have `node` and `npm` installed (via Homebrew, MacPorts or `.pkg`).

from `Terminal.app` of your Mac.

```sh
% git clone https://github.com/dankogai/js-combinatorics.git
% cd js-base64
% npm install http-server
% npx http-server
Starting up http-server, serving ./
Available on:
  http://127.0.0.1:8080
  http://172.16.80.224:8080
  http://172.16.80.177:8080
Hit CTRL-C to stop the server
```

IP addresses are subject change.

from your iPhone or iPad:

* open `http://172.16.80.224:8080/test/index.html` from Safari.  Choose IP address *other than* `127.0.0.1`.
* It should be working like the screen shot below:

![IMG_0068](https://user-images.githubusercontent.com/68812/131367054-3441f26b-a857-4c28-8922-aeecafed6bef.PNG)
