### ISSUE TITLE
高级语法在ie或者低版本浏览器不支持

### ISSUE THREAD

**Issue by wqq20170106** [dankogai/js-base64#142]
const b64chs = [...b64ch];

**Comment by wqq20170106** [comment]
@dankogai I‘m so sorry to trouble you, could you help me to resolve this issue if it is convenient for you. waiting...

**Comment by FOOSO** [comment]
应该需要自己来做兼容

**Comment by lizm-21** [comment]
@wqq20170106 解决了么

**Comment by dankogai** [comment]
https://github.com/dankogai/js-base64#heads-up
> In version 3.0 js-base64 switch to ES2015 module so it is no longer compatible with legacy browsers like IE (see below).

https://github.com/dankogai/js-base64#if-you-really-really-need-an-es5-version
> You can transpiles to an ES5 that runs on IE11. Do the following in your shell.
```
$ make base64.es5.js
```
