### ISSUE TITLE
If there is no “=” sign at the end. The decode string will be incorrect.

### ISSUE THREAD

**Issue by waylon-edmodo** [dankogai/js-base64#143]
eyJhdWQiOlsiY29tbW9uIiwiY3VzdG9tIl0sImV4cCI6MTYyNjg1ODYwNCwidXNlcl9uYW1lIjoiYWRtaW4xQDEiLCJqdGkiOiI1YzZkOTBmNi1hNTg0LTRkNWItOTc4Zi1mM2M2YTcyNDRhOTgiLCJjbGllbnRfaWQiOiJjbGllbnRfZmpsYW5kYW9fd2ViIiwic2NvcGUiOlsidHJ1c3QiXX0

If there is no “=” sign at the end. The decode string will be incorrect.

It can be parsed with other Base64 libraries. Such as crypto-js.
Other language also normal, such as: JAVA, OC

**Comment by waylon-edmodo** [comment]
![image](https://user-images.githubusercontent.com/51694657/124579613-df186f00-de81-11eb-94a2-b8854e3f8c0b.png)

**Comment by dankogai** [comment]
I could not reproduce your claim, at least on the recent version.  If you append `\u0000` to the decoded string and encode again, you will get:
 

`eyJhdWQiOlsiY29tbW9uIiwiY3VzdG9tIl0sImV4cCI6MTYyNjg1ODYwNCwidXNlcl9uYW1lIjoiYWRtaW4xQDEiLCJqdGkiOiI1YzZkOTBmNi1hNTg0LTRkNWItOTc4Zi1mM2M2YTcyNDRhOTgiLCJjbGllbnRfaWQiOiJjbGllbnRfZmpsYW5kYW9fd2ViIiwic2NvcGUiOlsidHJ1c3QiXX0A`

As you see `A` is added and without that the trailing `\u0000` does not happen.

<img width="1000" alt="From Clipboard" src="https://user-images.githubusercontent.com/68812/125400705-2e641f80-e3ed-11eb-8de4-4cdf951a1024.png">
