### ISSUE TITLE
Can not decode right string

### ISSUE THREAD

**Issue by EliteCheng** [dankogai/js-base64#145]
const base64 = require('js-base64');

console.debug(base64.encode('超长文件名的文件夹12345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890'));
//6LaF6ZW/5paH5Lu25ZCN55qE5paH5Lu25aS5MTIzNDU2Nzg5MDEyMzQ1Njc4OTAxMjM0NTY3ODkwMTIzNDU2Nzg5MDEyMzQ1Njc4OTAxMjM0NTY3ODkwMTIzNDU2Nzg5MDEyMzQ1Njc4OTAxMjM0NTY3ODkwMTIzNDU2Nzg5MDEyMzQ1Njc4OTA=
console.debug(base64.decode('6LaF6ZW/5paH5Lu25ZCN55qE5paH5Lu25aS5MTIzNDU2Nzg5MDEyMzQ1Njc4OTAxMjM0NTY3ODkwMTIzNDU2Nzg5MDEyMzQ1Njc4OTAxMjM0NTY3ODkwMTIzNDU2Nzg5MDEyMzQ1Njc4OTAxMjM0NTY3ODkwMTIzNDU2Nzg5MDEyMzQ1Njc4OTA=')); 
//超长文件名的文件夹12345678901234567890123456789012345678901234567890123456789001234567890123456789012345678901234567890

**Comment by dankogai** [comment]
It is decoding right.  Try

```javascript
const str = '超长文件名的文件夹12345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890';
console.debug(Base64.decode(Base64.encode(str)) == str); // true
```
