### ISSUE TITLE
When input is undefined it raises an error

### ISSUE THREAD

**Issue by jatinmehrotra** [dankogai/js-base64#151]
```
const a = undefined 
Base64.encode(a) -> raises an error 

TypeError: Cannot read property 'replace' of undefined
```

Probably if it returns undefined as a response, would be better.

**Comment by dankogai** [comment]
No it is not.  It is supposed to raise an exception because the type is wrong.  In TypeScript it is declared as:

```typescript
declare const encode: (src: string, urlsafe?: boolean) => string;
```

Unfortunately the compiled JS does not check types so your code SOMETIMES work (like browser consoles) when directly loaded.
