### ISSUE TITLE
Typo towards the end of the readme

### ISSUE THREAD

**Issue by savin2001** [dankogai/js-base64#154]
I noticed a typo on the readme  where it was written IE 11 compabile but should be compatible
![image](https://user-images.githubusercontent.com/44639335/170222352-8464b7ed-608c-4411-bd91-900a3ec83f6e.png)

**Comment by dankogai** [comment]
Thanks.  Fixed now.

https://github.com/dankogai/js-base64/commit/9ced30c0d0689a4cffe53876b8a001b75293fc55
