### ISSUE TITLE
Which version for VUE2.6.10？？？

### ISSUE THREAD

**Issue by CaiNiaoFeng** [dankogai/js-base64#156]
code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: @antv/x6-vue-shape@1.4.0
npm ERR! Found: vue@2.6.10
npm ERR! node_modules/vue
npm ERR!   peer vue@"^2.6.6" from @fullcalendar/vue@4.4.2
npm ERR!   node_modules/@fullcalendar/vue
npm ERR!     @fullcalendar/vue@"^4.3.1" from the root project
npm ERR!   peer vue@"^2.2.0" from @riophae/vue-treeselect@0.4.0
npm ERR!   node_modules/@riophae/vue-treeselect
npm ERR!     @riophae/vue-treeselect@"0.4.0" from the root project
npm ERR!   7 more (@vue/composition-api, @vue/test-utils, element-ui, ...)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer vue@"^2.6.12 || ^3.0.0" from @antv/x6-vue-shape@1.4.0
npm ERR! node_modules/@antv/x6-vue-shape
npm ERR!   @antv/x6-vue-shape@"^1.3.2" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: vue@3.2.37
npm ERR! node_modules/vue
npm ERR!   peer vue@"^2.6.12 || ^3.0.0" from @antv/x6-vue-shape@1.4.0
npm ERR!   node_modules/@antv/x6-vue-shape
npm ERR!     @antv/x6-vue-shape@"^1.3.2" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry

**Comment by dankogai** [comment]
You are banging on the wrong door.  Check the URL and try again.
