### ISSUE TITLE
Dual package hazard

### ISSUE THREAD

**Issue by jcbhmr** [dankogai/js-base64#168]
It would appear that this package encounters the dual package hazard with the base64 code being run potentially _twice_: once when `import`-ed and once when `require()`-ed.

https://nodejs.org/api/packages.html#packages_dual_package_hazard

![image](https://github.com/dankogai/js-base64/assets/61068799/db224439-c90b-49d3-890a-d2109ee1e27e)

This hasn't been an issue for me in practice, but it does happen!

```js
// app.cjs
async function main() {
  const { encode: encode1, decode: decode1 } = require('js-base64')
  const { encode: encode2, decode: decode2 } = await import('js-base64')

  console.log({ encode1, encode2, decode1, decode2 })
  console.log("encode1 === encode2", encode1 === encode2)
  console.log("decode1 === decode2", decode1 === decode2)
}
main();
```

```
{
  encode1: [Function: encode],
  encode2: [Function: encode],
  decode1: [Function: decode],
  decode2: [Function: decode]
}
encode1 === encode2 false
decode1 === decode2 false
```

This isn't terrible, it's just a quirk that should probably be fixed. 😉
(You can close this if this isn't a big deal.)

**Comment by dankogai** [comment]
This is more like a feature than an issue but I'll leave it open so users are aware of such possibilities like this 😉

**Comment by jcbhmr** [comment]
Would it perhaps be useful to add such documentation to the readme? 🤔 I think that might be better than a perpetually open issue 🤣

**Comment by dankogai** [comment]
https://github.com/dankogai/js-base64/pull/172 fixes this problem so closing.

**Comment by jcbhmr** [comment]
I don't think so? There's still two copies of the code: one that gets run when you `import "js-base64"` and one that gets run when you `require("js-base64")`.

```sh
@jcbhmr ➜ /workspaces/js-base64 (main) $ node
Welcome to Node.js v20.11.0.
Type ".help" for more information.
> let esm = await import("js-base64")
undefined
> let cjs = require("js-base64")
undefined
> esm
[Module: null prototype] {
  // ...
}
> cjs
{
  // ...
}
> esm.atob === cjs.atob
false
> esm.Base64 === cjs.Base64
false
> 
```

using commit 53644d0db19d15b035a32a63f479664e86a33b5b

**Comment by jcbhmr** [comment]
The solution is  to  treat one implementation  as "the implementation" (probably the CJS one) and then just re-export  that in the ESM version like  this:

```js
import cjs from "./base64.js";

export const {
  version,
  VERSION,
  atob,
  atobPolyfill,
  btoa,
  btoaPolyfill,
  fromBase64,
  toBase64,
  encode,
  encodeURI,
  encodeURL,
  utob,
  btou,
  decode,
  isValid,
  fromUint8Array,
  toUint8Array,
  extendString,
  extendUint8Array,
  extendBuiltins,
  Base64,
} = cjs;
```

```sh
@jcbhmr ➜ /workspaces/js-base64 (main) $ node
Welcome to Node.js v20.11.0.
Type ".help" for more information.
> let esm = await import("js-base64")
undefined
> let cjs = require("js-base64")
undefined
> esm.atob === cjs.atob
true
> esm.Base64 === cjs.Base64
true
> 
```

**Comment by dankogai** [comment]
It is not only okay but necessary for `esm.atob === cjs.atob` to be `false` even their contents are identical.  Consider:

```javascript
const funcA = function(){}
const funcB = function(){}
funcA === funcB // false
```

> I don't think so? There's still two copies of the code: one that gets run when you `import "js-base64"` and one that gets run when you `require("js-base64")`.
> 
> ```shell
> @jcbhmr ➜ /workspaces/js-base64 (main) $ node
> Welcome to Node.js v20.11.0.
> Type ".help" for more information.
> > let esm = await import("js-base64")
> undefined
> > let cjs = require("js-base64")
> undefined
> > esm
> [Module: null prototype] {
>   // ...
> }
> > cjs
> {
>   // ...
> }
> > esm.atob === cjs.atob
> false
> > esm.Base64 === cjs.Base64
> false
> > 
> ```
> 
> using commit [53644d0](https://github.com/dankogai/js-base64/commit/53644d0db19d15b035a32a63f479664e86a33b5b)

**Comment by jcbhmr** [comment]
> ```js
> const funcA = function(){}
> const funcB = function(){}
> funcA === funcB // false
> ```

You're absolutely right! The functions _would_ be different! And that's actually exactly what's happening. There's _two duplicate pieces of code running_ each creating their own function  that is therefore _NOT_ `esm.theExport === cjs.theExport` to the  other one. When you `import("js-base64")` it runs the `base64.mjs` due to the `import` condition being satisfied in package.json. Then when you (or one of your dependencies that isn't using ESM yet) uses `require("js-base64")` it gets _a different file_ from `base64.js` (CJS) which then _executes a different version of the  code_ so  that you end up with one execution for the ESM and then a second execution for the CJS.

This rears its head in bundlers since bundlers will then include _both_ the base64.js and the base64.mjs file effectively making the library 2x the size lol.

The solution  is  to delegate to the "canonical" CJS function and wrap it in a  nice ESM  interface with appropriate named exports. Normally Node.js does this for you using https://github.com/nodejs/cjs-module-lexer to extract  the named  exports so you can normally do `import { hello } from "./x.cjs"` but since base64.js doesn't  have  those tokens you need  the .mjs wrapper to explicitly pluck the named exports  out  of the CJS object.

The  official Node.js  docs recommend  this solution:

> Approach #1: Use an ES module wrapper[#](https://nodejs.org/api/packages.html#approach-1-use-an-es-module-wrapper)

>
> ```js
> import cjsModule from './index.cjs';
> export const name = cjsModule.name;
> export default cjsModule; 
> ```
> 
> https://nodejs.org/api/packages.html#approach-1-use-an-es-module-wrapper

**Comment by dankogai** [comment]
Sure it doubles the size of the library but it is still 8.3kB.  It also make both cjs and mjs **stand alone** which matters a lot especially when you want to use CDN versions like:

```html
<script src="https://cdn.jsdelivr.net/npm/js-base64@3.7.6/base64.min.js"></script>
```

```
npm notice === Tarball Details === 
npm notice name:          js-base64                               
npm notice version:       3.7.6                                   
npm notice filename:      js-base64-3.7.6.tgz                     
npm notice package size:  8.3 kB                                  
npm notice unpacked size: 38.7 kB                                 
npm notice shasum:        6ccb5d761b48381fd819f9ce04998866dbcbbc99
npm notice integrity:     sha512-NPrWuHFxFUknr[...]OgPQ6Zq+EDiTA==
npm notice total files:   7                                       
```

**Comment by jcbhmr** [comment]
Yes, it's minor. I'll drop this since it's OK to duplicate code 👍

For CDNs you're right that raw esm code is nice. I'm a user of https://esm.sh and https://esm.run (from jsDelivr) so I haven't had reason to use the raw .min.js file directly before 🤷‍♂️
