### ISSUE TITLE
Does chunk the buffer affect multibyte characters?

### ISSUE THREAD

**Issue by JC-Ge** [dankogai/js-base64#170]
https://github.com/dankogai/js-base64/blob/34cd9344dae428adbde8084e28339a591bbdf7e5/base64.ts#L71

Does chunk the buffer affect multibyte characters?
If there is no effect, I would like to know why

**Comment by dankogai** [comment]
This is to prevent `_fromCC` (which is really `String.fromCharCode.bind(String)`) from getting too many arguments.  The number of arguments a function can receive is not that big.  0x1000 = 4096 is a conservative value which works on all JS implementations that this module supports.  See also:

* https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/fromCharCode
* https://stackoverflow.com/questions/12710001/how-to-convert-uint8-array-to-base64-encoded-string/12713326#12713326

**Comment by JC-Ge** [comment]
I know maxargs how to work, but my doubt is the following question

**Comment by JC-Ge** [comment]
[[[Again,]() note that this is only correct if your buffer only contains non-multibyte ASCII characters:](https://stackoverflow.com/questions/12710001/how-to-convert-uint8-array-to-base64-encoded-string/12713326#12713326)]([[Again,]() note that this is only correct if your buffer only contains non-multibyte ASCII characters:](https://stackoverflow.com/questions/12710001/how-to-convert-uint8-array-to-base64-encoded-string/12713326#12713326))

**Comment by JC-Ge** [comment]
I see in 

[https://stackoverflow.com/questions/12710001/how-to-convert-uint8-array-to-base64-encoded-string/12713326#12713326](https://stackoverflow.com/questions/12710001/how-to-convert-uint8-array-to-base64-encoded-string/12713326#12713326) 
**this is only correct if your buffer only contains non-multibyte ASCII characters**

Doesn't this code have this problem？

**Comment by dankogai** [comment]
Look the source carefully.  It is within `_fromUint8Array()` which deals with `Uint8Array` not `String`.  Always single-byte.

**Comment by JC-Ge** [comment]
Always single-byte?
In this case `new TextEncoder().encode('我');// [230,136,145]`, is 3 byte
