### ISSUE TITLE
有没有方法可以准确判断是否是base64格式的

### ISSUE THREAD

**Issue by ytanck** [dankogai/js-base64#178]
比如MTMzNjY2Njg4ODg 和 MTMzNjY2Njg4ODg=
后面多了个‘=’，但都可以base64解码成功。但有些方法判断 isBase64（'MTMzNjY2Njg4ODg'）返回false

**Comment by zicz** [comment]
base64 的长度不是 4 的倍数，需要在末尾添加“=”

The length of base64 is not a multiple of 4, and '=' needs to be added at the end。

**Comment by dankogai** [comment]
Sorry for overlooking this issue.

This module does not have `isBase64()`.  It does have `isValid()`.
