### ISSUE TITLE
ES6 import feels wrong

### ISSUE THREAD

**Issue by reggi** [dankogai/js-base64#24]
With CommonJS you can add an param to the end of the require statement. 

``` javascript
var Base64 = require('./base64.js').Base64;
Base64.encode(data)
```

In ES6 you can't so you have to call it like this and it just feels wrong, and is super confusing.

``` javascript
import base64 from "js-base64"
base64.Base64.encode(data)
```

**Comment by omarmeky** [comment]
Try:

import {Base64} from "js-base64"

**Comment by ComLock** [comment]
Both 
import { Base64 } from '/node_modules/js-base64/base64.js';
and
import { Base64 } from '/node_modules/js-base64/base64.min.js';

Give me the following error:
TypeError: Cannot get property "Base64" of null

On line 14
var _Base64 = global.Base64;

In other words global is null...

I'm trying use this module with Enonic XP, which is not a node project.

**Comment by stlemon** [comment]
import {Base64} from "js-base64" also error
"unable to resolve module buffer from ......"
who can fix it ?

**Comment by gbabula** [comment]
@stlemon `import {Base64} from "js-base64"` works correctly.

**Comment by 12343954** [comment]
@stlemon 

`npm i -S buffer`

to fix it
