### ISSUE TITLE
CommonJS support in browser

### ISSUE THREAD

**Issue by btknorr** [dankogai/js-base64#27]
Frameworks like Component, Duo, etc... all let you use require() in the browser.  Unfortunately these lines of code causes js-base64 not to be usable by them:

    if (typeof module !== 'undefined' && module.exports) {
        buffer = require('buffer').Buffer;
    }

Is there a better way to determine if you are running in node?  If so we can use this library in the browser using CommonJS.  Thanks!

**Comment by MQQiang** [comment]
+1
comment these line save the problem but not beautiful

**Comment by dankogai** [comment]
709d17d6819acf50e2b1799bdb7bace4781e1ea7 closed the issue as:

````javascript
if (typeof module !== 'undefined' && module.exports) {
        try {
            buffer = require('buffer').Buffer;
        } catch (err) {}
    }
````

**Comment by nallwhy** [comment]
Same problem with SystemJS + Zone
