### ISSUE TITLE
Error occurs when working with Meteor

### ISSUE THREAD

**Issue by lzh0379** [dankogai/js-base64#28]
At the bottom of file base64.js, the variable "global" is undefined in the context.
When I use visualize.js from Jaspersoft in Meteor, error occurs.

============================
```javascript
    // that's it!
})(this);

if (this['Meteor']) {
    Base64 = global.Base64; // for normal export in Meteor.js
}
```

**Comment by dankogai** [comment]
Then https://github.com/dankogai/js-base64/commit/1f5d03df40a913a83c7a9541c07c6eba3c19674d should fix it.  If it doesn't please reopen this issue.

**Comment by lzh0379** [comment]
Great, it should be like that. Thanks!
