### ISSUE TITLE
Import js error, Chrome Version 41.0.2272.101 m (64-bit)

### ISSUE THREAD

**Issue by baishui2004** [dankogai/js-base64#30]
Import: base64.min.js
Chrome error:Uncaught SyntaxError: Invalid regular expression: /[Ã€-ÃŸ][Â€-Â¿]|[Ã -Ã¯][Â€-Â¿]{2}|[Ã°-Ã·][Â€-Â¿]{3}/: Range out of order in character class
Then Import base64.js work well. And base64.min.js, base64.js work well in ie.

**Comment by cthorner** [comment]
I'm seeing this as well. Looks like the minified version coverts The RegExp for the decoder from:

```javascript
 var re_btou = new RegExp([
        '[\xC0-\xDF][\x80-\xBF]',
        '[\xE0-\xEF][\x80-\xBF]{2}',
        '[\xF0-\xF7][\x80-\xBF]{3}'
    ].join('|'), 'g');
```
to
```javascript
var re_btou=new RegExp(["[À-ß][<U+0080>-¿]","[à-ï][<U+0080>-¿]{2}","[ð-÷][<U+0080>-¿]{3}"].join("|"),"g");
```
which for some reason, shows up as:

```javascript
v = new RegExp(["[Ã€-ÃŸ][Â€-Â¿]", "[Ã -Ã¯][Â€-Â¿]{2}", "[Ã°-Ã·][Â€-Â¿]{3}"].join("|"),"g")
```
when it is loaded in Chrome(don't ask me why).

**Comment by dankogai** [comment]
Works OK w/ current Chrome.
