### ISSUE TITLE
 Base64 decode to GB2312   is ok,but Base64 decode to utf-8 is bad

### ISSUE THREAD

**Issue by cristicmf** [dankogai/js-base64#34]
for example
Base64.decode('QUFmdHA6Ly9keWdvZDE6ZHlnb2QxQGQxOTguZHlnb2QubmV0OjExMjMvt8ezz87wyMVEVkTN6tX7uN/H5dDe1f2w5i9btefTsMzszMN3d3cuZHlnb2QubmV0XbfHs8/O8MjFY2Qxo6jN6tX7uN/H5dDe1f2w5qOpLnJtdmJaWg==');

**Comment by dankogai** [comment]
See https://github.com/dankogai/js-base64/issues/36
