### ISSUE TITLE
encodeURI() is not adding correct padding

### ISSUE THREAD

**Issue by benbini** [dankogai/js-base64#37]
`Base64.encodeURI()` is not adding correct padding to some input, such as "賦-卷十四".

Baseline Python 3 encoding:
```
base64.urlsafe_b64encode(bytes("賦-卷十四",encoding="utf-8")).decode('utf-8')
   '6LOmLeWNt-WNgeWbmw=='
```

While the `Base64.encodeURI()` output is: `6LOmLeWNt-WNgeWbmw`.

Worth noting that the output of `Base64.encode()` is padded correctly but of course includes non-URLsafe characters: `6LOmLeWNt+WNgeWbmw==`.

EDIT: This is probably happening because you are deleting "=" from uri_escaped values:
```
  var encode = function(u, urisafe) {
       return !urisafe ? _encode(String(u))  : _encode(String(u)).replace(/[+\/]/g, function(m0)
 {return m0 == '+' ? '-' : '_';}).replace(/=/g, ''); };
```
Why are you doing this??

**Comment by dankogai** [comment]
According to [RFC4648](https://tools.ietf.org/html/rfc4648),  padding can be omitted when the size of the data is obvious.

> In some circumstances, the use of padding ("=") in base-encoded data
   is not required or used.  In the general case, when assumptions about
   the size of transported data cannot be made, padding is required to
   yield correct decoded data.

FYI [MIME::Base64](https://metacpan.org/pod/MIME::Base64) of Perl5 also omits padding:

````
perl -MMIME::Base64 -E 'say MIME::Base64::encode_base64url("賦-卷十四")'
6LOmLeWNt-WNgeWbmw
````

And when you do add the padding, it must also be percent-encoded, making it less useful.

So I'll leave it that way.
