### ISSUE TITLE
TypeScript basic implementation

### ISSUE THREAD

**Issue by DenisCarriere** [dankogai/js-base64#38]
I've added a basic Typescript Definition to this project, however I was having issue understanding the more complex methods and functionality.

If anyone could follow up and add those extra definitions.

Add methods:
- [x] encode
- [x] encodeURI
- [x] decode
- [ ] atob
- [ ] btoa
- [ ] fromBase64
- [ ] toBase64
- [ ] utob
- [ ] btou
- [ ] noConflict

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/88fca07022ae6549a09965bf1316a1f5e34e471b/js-base64/js-base64.d.ts

**Comment by ssougnez** [comment]
HI,

I'm currently using these declarations along with angular2 and webpack and I'm having this issue:

> Cannot redeclare block-scoped variable 'Base64'

Apparently, it would come from this line: "const Base64: Base64" in the d.ts file. 

As it is definition file, my project works anyway but it would be nice to fix this.

Thanks a lot ;-)

**Comment by DenisCarriere** [comment]
@ssougnez You're right, the definition doesn't look right. I'll send a PR to DT.

**Comment by DenisCarriere** [comment]
@ssougnez The fix has been merged, try it out and let me know if the issue is still happening.

```bash
$ typings install --save --global dt~js-base64
```

**Comment by ssougnez** [comment]
Hello,

sorry but I'm using TypeScript 2.0 so I'm using "@types/js-base64" package. Do you think it's possible to update these for me to test your fix ?

**Comment by DenisCarriere** [comment]
@ssougnez It takes a week before they process the DT library, I'd suggest you use `dt~j-base64` until the `@types/js-base64` gets updated.

Comment from DT @andy-ms

> We have to do manual porting of the latest changes to master to the types-2.0 branch. This should happen about once a week.

**Comment by ssougnez** [comment]
Hi,

as it was not a blocking issue, I prefered to wait until it is merged to @types and use this version. However, this still does not work, now I have two issues:

> ERROR in [default] ...\@types\js-base64\index.d.ts:23:10 
> Cannot redeclare block-scoped variable 'Base64'.
> 
> ERROR in [default] ...\@types\js-base64\index.d.ts:54:4 
> Duplicate identifier 'export='.

FYI, I'm also using the @types for "node" and "corejs" (I don't know, maybe the issue could come from that).

I also deleted my "node_modules" folder and did a "npm install" to be sure to be in a clean state.

Regards

**Comment by andy-ms** [comment]
Typings can be included directly with a project; that way you don't need to publish in multiple places. See the [handbook](http://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html). A package does not have to be authored in TypeScript for this to work. Tell us if you do this so we can deprecate `@types/js-base64`.

**Comment by DenisCarriere** [comment]
@ssougnez Can you try modifying the Typings inside your npm `@types` directory and see if this new fix works, if not try figuring out what works and send a PR to DefinitelyTyped.
