### ISSUE TITLE
Fails in the browser with Systemjs

### ISSUE THREAD

**Issue by guidefreitas** [dankogai/js-base64#41]
The bellow verification fails in the browser when using SystemJS (like with Angular 2 + angular2-jwt). This library tries to load Buffer without success.

   if (typeof module !== 'undefined' && module.exports) {
        try {
            buffer = require('buffer').Buffer;
        } catch (err) {}
    }

Not sure how to fix it though.

**Comment by flemeur** [comment]
I am experiencing the same issue when using SystemJS builder. I get `Error on fetch for buffer`

The problem must be related to the build being run by nodejs. It only happens durring production builds where the command is something like `gulp build --production && node systemjs.builder.js`
