### ISSUE TITLE
SyntaxError: invalid range in character class

### ISSUE THREAD

**Issue by EvgenyGusev** [dankogai/js-base64#5]
Hi. I use coffeescript and Hem (0.3.2) to build it. When i include base64.min.js to libraries, i get error: "SyntaxError: invalid range in character class". It is some problem with coffeescript, hem, or base64? I can use non minified version without any problem.

**Comment by garex** [comment]
They are differs (vesions). Better to use own minifier. Also not all regexps created through RegExp.
May be coffeescript breaks brain on it. Try your own minifier through some grunt and report back if it helps.
