### ISSUE TITLE
2.2.0 release breaks the library

### ISSUE THREAD

**Issue by tylerlong** [dankogai/js-base64#50]
```
console.log(require('js-base64'))
```

![image](https://user-images.githubusercontent.com/733544/30250373-b40b4718-967f-11e7-8e85-731c35af6fd5.png)

```
var Base64 = require('js-base64').Base64;
```

`Base64` is `undefined`.

**Comment by dankogai** [comment]
try `npm install --save js-base64` .   If you are attempting to do so in the git repo, you have to go like `var Base64 = require('./base64').Base64;` instead.

**Comment by tylerlong** [comment]
It's not that simple.  I am not a Node.js newbie :)

I did it in node.js and compiled it into browser. Then run it in browser.

The same code works with 2.1.9. 

A real example is https://github.com/mermaidjs/mermaid-live-editor/blob/master/package.json#L15

Try `yarn upgrade js-base64` and you will see the project stops working.

**Comment by dankogai** [comment]
It could be because of the tag.  I made sure that https://github.com/dankogai/js-base64/commit/471f1c8e938d7c34d77d9fddf5fc9ac115d21e98 is tagged 2.2.0 and https://github.com/dankogai/js-base64/commit/9192c510f5ed604d9e9dcdbb6760eba5a9eb2851 is tagged 2.1.9.

**Comment by tylerlong** [comment]
I installed the package via npm instead of bower, I don't think GitHub tag matters.

**Comment by tylerlong** [comment]
I confirm that 2.3.0 works.
