### ISSUE TITLE
Base64 URL safe removes padding

### ISSUE THREAD

**Issue by Saurbaum** [dankogai/js-base64#54]
If I put 
> Полтава 

through the encoder I get 
> 0J/QvtC70YLQsNCy0LA=

If I enable the URL safe method I get this

> 0J_QvtC70YLQsNCy0LA

Which has removed the trailing = padding as well as the expected conversion to URL safe

**Comment by dankogai** [comment]
cf. https://en.wikipedia.org/wiki/Base64#Variants_summary_table

**Comment by guyskk** [comment]
Many services require base64 padding, it would be better to allow configure padding behavior.

My workaround:

```javascript
Base64.encode(inputStr).replace('+', '-').replace('/', '_')
```
