### ISSUE TITLE
base64 is not a function in Node v4

### ISSUE THREAD

**Issue by yjcxy12** [dankogai/js-base64#56]
I'm getting `base64 is not a function` error after yesterday's change which I believe is these changes.
https://github.com/dankogai/js-base64/commit/471f1c8e938d7c34d77d9fddf5fc9ac115d21e98#diff-ec222f0dcab7350b590a36cd0fa147d0R74

Our CI system is stuck in Node v4, and this library being dependency in `postcss` is failing our builds.

Is there any solution to this issue?

related to #55

**Comment by JabbyPanda** [comment]
> In node 5.3 & below, you need to use the buffer constructor (ie: new Buffer) instead of Buffer.from

from https://stackoverflow.com/posts/42261035

**Comment by yjcxy12** [comment]
Found this on `postcss` https://github.com/postcss/postcss/commit/dfbe7c8231b6736018caddaa897b51759b0eb6a3#diff-5963ea3ed043e2627356b48917d86a63L125

Is it reasonable we do the same `Buffer.from && Buffer.from !== Uint8Array.from` to check `buffer.from`?

**Comment by dankogai** [comment]
should be fixed in https://github.com/dankogai/js-base64/commit/819e9b42e797b9cc6fc9ca069770a9fbaacb26ae .
