### ISSUE TITLE
License Issue

### ISSUE THREAD

**Issue by mlucool** [dankogai/js-base64#58]
Hi,

The license should be `BSD-3-Clause` not `BSD 3-Clause` in package.json.
See: https://spdx.org/licenses/BSD-3-Clause.html

Thanks for fixing!

**Comment by dankogai** [comment]
done in https://github.com/dankogai/js-base64/commit/819e9b42e797b9cc6fc9ca069770a9fbaacb26ae .  Thank you for reporting.
