### ISSUE TITLE
Fails to decode utf-8 string using both atob and decode

### ISSUE THREAD

**Issue by christofferskog** [dankogai/js-base64#63]
The correct letter here should be "ä".

`Base64.atob(QWZm77+9cnNmb2t1cwpBZmbvv71yc2Zva3VzCg==);`

Gives:
Affï¿½rsfokus

`Base64.decode(QWZm77+9cnNmb2t1cwpBZmbvv71yc2Zva3VzCg==);`

Gives:
Aff�rsfokus

**Comment by dankogai** [comment]
No.  Your base64 encoded string is wrong.  Base64.decode("`Affärsfokus\nAffärsfokus\n`") is
`QWZmw6Ryc2Zva3VzCkFmZsOkcnNmb2t1cwo=`
not
`QWZm77+9cnNmb2t1cwpBZmbvv71yc2Zva3VzCg==`

**Comment by christofferskog** [comment]
I can't encode it any different, I get the csv file from a file input then I read it with the `FileReader`. Which gives me what I posted above.
