### ISSUE TITLE
Conflict with Moment.js

### ISSUE THREAD

**Issue by guili-lcj** [dankogai/js-base64#67]
I import Moment.js  use script tag , then import js-base64 in the same way after Moment.js. js-base64 may cover the window.moment object.

window 10
chrome  62.0.3202.94

**Comment by tkarls** [comment]
This happened to me too.

**Comment by tkarls** [comment]
This is the line that is causing it

https://github.com/dankogai/js-base64/blob/master/base64.js#L13

A quick search does not indicate that the moment variable is ever used. So perhaps it can simply be removed? Why ever it was added in the first place.

**Comment by ryanjkelly** [comment]
This broke some of our pages as well. We had to revert back to `2.3.2`.

**Comment by dankogai** [comment]
Fixed the code accordingly, thank you!

**Comment by dankogai** [comment]
I have reverted the change by pulling https://github.com/dankogai/js-base64/pull/71.  I wrote a test html that loads base64.js before and after moment.js and they both worked OK.
