### ISSUE TITLE
"Uint8Array" Undefined error in ie8

### ISSUE THREAD

**Issue by zhoushirong** [dankogai/js-base64#68]
when i use typescript and webpack compile
`
import { base64 } from 'js-base64';
base64.encode('string');
...
`

**ie8 throw a error:"Uint8Array" Undefined**

when i debugging in base64.js, find that 

`buffer = require('buffer').Buffer;`
buffer is exist，but Uint8Array is not, so ‘Uint8Array.from’ throw error

The number of lines that are wrongly reported is 163 and 82: 
`buffer.from && buffer.from !== Uint8Array.from ? ...`

**Comment by xingzhanF** [comment]
后来解决了吗?

**Comment by dankogai** [comment]
Would you try https://github.com/dankogai/js-base64/commit/5f0a06e235dc31da6d98583a8b5334b59cb858aa ?  If that works I'll version++.

**Comment by dankogai** [comment]
ie8 is way obsolete but naively assuming the presence of `Uint8Array` is not good practice.
