### ISSUE TITLE
why there's a '#dankogai.js#' file in test directory?

### ISSUE THREAD

**Issue by gohonsen** [dankogai/js-base64#69]
download js-base64  2.4.1 from https://registry.npmjs.org/js-base64/-/js-base64-2.4.1.tgz, there's a '#dankogai.js#' file in js-base64/test directory.  I found that because the file caused fis package failed.

**Comment by marols** [comment]
@dankogai I have also noticed the file above. It has caused my build to fail as well. From the contents of it it seems to be a copy of the file `dankogai.js` which is also contained within the `test` directory.

Is the file intentionally placed there or is it an error of some sort?

The file does not exist in version 2.4.0 of the package.

**Comment by dankogai** [comment]
I don't know but looks like it is a temporary emacs file.  I version++'ed and made sure https://registry.npmjs.org/js-base64/-/js-base64-2.4.2.tgz does not contain the fuzz.

**Comment by marols** [comment]
Sweet, good work!

Thanks
