### ISSUE TITLE
Missing babel-preset-es2015 dependency

### ISSUE THREAD

**Issue by BrodaNoel** [dankogai/js-base64#75]
After install it in React Native, I'm getting a error due to `babel-preset-es2015` is not added as a dependency in my code.

**Comment by dankogai** [comment]
`js-base64` itself is standalone, has no dependency unless you use it with React Native in which case `babel-preset-es2015` is required.  Just

```
npm install --save babel-preset-es2015
```

before

```
npm install --save js-base64
```

**Comment by craftzdog** [comment]
This is because `.babelrc` file is included in the npm package.
Please add `.npmignore` to exclude `.babelrc` from the published package.

**Comment by BrodaNoel** [comment]
@dankogai ^

**Comment by dankogai** [comment]
Fixed as @craftzdog suggested in 
https://github.com/dankogai/js-base64/commit/3e048fce9f749e6f9738d130e5ca20c4a2dd9d43 .
`npm published` as well.

**Comment by craftzdog** [comment]
Thank you for the quick fix, @dankogai!
