### ISSUE TITLE
Unable to resolve module `buffer` on React Native

### ISSUE THREAD

**Issue by maximten** [dankogai/js-base64#79]
```
    if (typeof module !== 'undefined' && module.exports) {
        try {
            buffer = require('buffer').Buffer;
        } catch (err) {}
    }
```

This cause an error on React Native:
```
Error: Unable to resolve module `buffer`
```

**Comment by ethan605** [comment]
I encounter this error today, one (possible ?) solution is install extra [`buffer`](https://github.com/feross/buffer) package. But I think this should appears in `js-base`'s `dependencies` list (for now there's no modules in this list yet)

**Comment by dankogai** [comment]
It may be because babel preset `es2015` is replaced with `env`.  At any rate version 2.4.7 now detects if it is running on React Native and skip loading `buffer`.
