### ISSUE TITLE
What's the differents between this and 'Buffer'?

### ISSUE THREAD

**Issue by YouCii** [dankogai/js-base64#81]
I can also encode/decode strings using Buffer that only dependent on one library `"buffer": "^5.2.0"`
```
import {Buffer} from "buffer"
export default class EncodeUtils {
    static encodeBase64Content(content) {
        return new Buffer(content).toString('base64')
    }
    static decodeBase64Content(base64Content) {
        return new Buffer(base64Content, 'base64').toString();
    }
}
```

**Comment by dankogai** [comment]
`base64` of `Buffer` corresponds to `atob` and `btoa`, which differ from `.encode` and `.decode` of `Base64`.

https://github.com/dankogai/js-base64#decode-vs-atob-and-encode-vs-btoa
