### ISSUE TITLE
Error when upgrading from 2.4.8 to 2.4.9

### ISSUE THREAD

**Issue by MatissJanis** [dankogai/js-base64#83]
```
Error: Failed to execute 'atob' on 'Window': The string to be decoded is not correctly encoded.
        error properties: Object({ INDEX_SIZE_ERR: 1, DOMSTRING_SIZE_ERR: 2, HIERARCHY_REQUEST_ERR: 3, WRONG_DOCUMENT_ERR: 4, INVALID_CHARACTER_ERR: 5, NO_DATA_ALLOWED_ERR: 6, NO_MODIFICATION_ALLOWED_ERR: 7, NOT_FOUND_ERR: 8, NOT_SUPPORTED_ERR: 9, INUSE_ATTRIBUTE_ERR: 10, INVALID_STATE_ERR: 11, SYNTAX_ERR: 12, INVALID_MODIFICATION_ERR: 13, NAMESPACE_ERR: 14, INVALID_ACCESS_ERR: 15, VALIDATION_ERR: 16, TYPE_MISMATCH_ERR: 17, SECURITY_ERR: 18, NETWORK_ERR: 19, ABORT_ERR: 20, URL_MISMATCH_ERR: 21, QUOTA_EXCEEDED_ERR: 22, TIMEOUT_ERR: 23, INVALID_NODE_TYPE_ERR: 24, DATA_CLONE_ERR: 25, code: 5 })
```

**Comment by MatissJanis** [comment]
Sure.

Here's a demo: https://jsfiddle.net/ygjn2fma/1/ (copy&paste of the minified code from this repo + oneliner throwing an exception).

v2.4.8:
```
console.log(Base64.decode('hello')) // 'hello'
 ```

v2.4.9:
```
console.log(Base64.decode('hello')) // Exception
 ```

**Comment by dankogai** [comment]
This is a correct behavior.  `hello` is an  **INVALID** Base64.  `Base64.decode` uses `atob` if present and how it handles invalid Base64 depends on its platform.  Recent ones are more strict. 

Or did you mean:

```javascript
Base64.encode('hello'); // 'aGVsbG8='
Base64.decode('aGVsbG8='); // 'hello'
```

**Comment by MatissJanis** [comment]
I actually meant `decode`. Since there is no method for checking the validity of the input, I was attempting to decode the input & compare the decoded result with the input. If they match -> the base64 is invalid.

The fact is that this is a breaking change and should be treated as such. I was lucky enough to have unit tests that caught this issue. Others may not have tests.
