### ISSUE TITLE
eval being blocked by content-security policy

### ISSUE THREAD

**Issue by travi** [dankogai/js-base64#85]
after upgrading to the latest version, we are now getting reports about javascript evaluation being blocked by our content-security policy do to the use of `eval`. looks like it was introduced as part of https://github.com/dankogai/js-base64/issues/82. any chance there is a alternative solution to that problem that wouldn't trigger policy exceptions like this?

**Comment by dankogai** [comment]
YOUR LOCAL policy is not enough to justify the change but I admit this kind of `eval` is evil, however necessary it may be.  But I would like to keep `base64.js` cross-platform and dependence free.  The problem is that there are too many platforms from good old `<script src=` to transpilers…

Any idea?

**Comment by travi** [comment]
> YOUR LOCAL policy is not enough to justify the change

i certainly wouldnt push too hard to support it just for our policy, but it is worth being aware that all CSPs block eval by default, so it's quite likely that others that have defined _a_ policy will also have `eval` blocked. it has to be explicitly allowed, so its unlikely that a team that has gone through the steps of implementing a policy would be willing to allow it for this package

> The problem is that there are too many platforms

i understand that this could be tricky and i did see that you went through a bunch of options in the other ticket. unfortunately, i dont understand the problem you were solving there well enough to offer a better option. mostly wanted to at least raise visibility that the current solution causes issues for us and likely others that have implemented a CSP in hopes that there might still be alternatives available.

currently we've pinned the previous version, but always have hope to stay current with new releases, so happy to test from our side if verifying our context is helpful.

**Comment by jineshshah36** [comment]
Just want to add that we too are seeing this issue, thought it's not a big deal since it doesn't affect usage in the browser, just keep getting false positives for CSP

**Comment by jineshshah36** [comment]
What if you exported multiple bundles for different environments. Then, we could import in the following manner:

```ts
import { Base64 } from "js-base64/browser"
```

```ts
const { Base64 } = require("js-base64/node")
```

and so on

**Comment by jineshshah36** [comment]
Another option is to do the following to detect react native:

```js
if (typeof document != 'undefined') {
  // I'm on the web!
}
else if (typeof navigator != 'undefined' && navigator.product == 'ReactNative') {
  // I'm in react-native
}
else {
  // I'm in node js
}
```

Taken from here: https://stackoverflow.com/questions/39468022/how-do-i-know-if-my-code-is-running-as-react-native

**Comment by jineshshah36** [comment]
See https://github.com/dankogai/js-base64/pull/90 for details

**Comment by dankogai** [comment]
Pulled #90.  Thank you!

**Comment by dankogai** [comment]
Ouch.  I forgot to recall THAT IS NOT THE POINT.  The point of `eval()` is to hide `require('Buffer')` from `Bundler`.  Detecting React Native is not good enough (and I was tried and failed before).  See:

https://github.com/dankogai/js-base64/issues/82

**Comment by shrpne** [comment]
I think the best solution is to split base64.js into two files, one for browser and one for nodejs. Add `browser` field to the package.json to let it choose right version.
- it will solve `eval` issue
- it will decrease file size (no more browser/node checks)

**Comment by andrewmclagan** [comment]
@shrpne I agree, with modern ES6 exports this should be a cinch?

**Comment by BernhardPosselt** [comment]
Isn't there an easy way to remove eval?

Check if require is defined, then try to require the stuff and catch the error?

**Comment by BernhardPosselt** [comment]
Ah, nevermind. Why not build a separate version for reactive native in that case if their build tool is the problem?

**Comment by BernhardPosselt** [comment]
Or simply remove the buffer dependency if being very cross platform is your goal.

**Comment by mdsummers** [comment]
Seeing this issue too. Bundling with webpack the `eval` is attempted at runtime, violating CSP.

v2.4.8 appears to be the last version without the `eval`.

**Comment by stefanw** [comment]
I see this as well. The code works, but I'm hit with CSP reports. It looks like a more robust browser check would fix this.

**Comment by Kwaadpepper** [comment]
> Seeing this issue too. Bundling with webpack the `eval` is attempted at runtime, violating CSP.
> 
> v2.4.8 appears to be the last version without the `eval`.

Same issue on my webpack project, so will stick with 2.4.8 for now. Btw security should be every one's priority since secure mechanisms exists, we should all comply with them as they make our life easier in the end.

**Comment by dankogai** [comment]
https://github.com/dankogai/js-base64/commit/0df4bd24c08fc6143577b0fac7aa5a323eb52660

**Comment by andrewmclagan** [comment]
___---===>>> AMAZING <<<===---___ 

@dankogai We really appreciate your work. This resolves allot of issues for us, just thought we should recognise all your hard work!
