### ISSUE TITLE
is there a to Uint8Array method?

### ISSUE THREAD

**Issue by AlucardShi** [dankogai/js-base64#87]
可以添加一个base64 String和Uint8Array互转的方法吗

**Comment by ZhouHanXiao** [comment]
请问怎么识别这个字符串是经过base64编码的？

**Comment by suedar** [comment]
Uint8Array转base64只能用`.toString(64)`，现在不支持，而且会报错

**Comment by dankogai** [comment]
See https://github.com/dankogai/js-base64/commit/fc1e6a7f0dfb26651e64f58b40781482c4cd5c6c
