### ISSUE TITLE
Base64 passed from the mobile phone camera base64, decoding failed

### ISSUE THREAD

**Issue by Jack-rainbow** [dankogai/js-base64#89]
I want to decode the base64 sent by the mobile phone camera, but it is gibberified by base64. I want to ask, what am I ignoring? By default, window.atob decoding is also a mess？
![image](https://user-images.githubusercontent.com/20368037/50399204-b5623580-07b8-11e9-8a68-12a0cdc0e604.png)

**Comment by dankogai** [comment]
https://github.com/dankogai/js-base64#decode-vs-atob-and-encode-vs-btoa
