### ISSUE TITLE
WhiteSource scan warning 

### ISSUE THREAD

**Issue by Sprokopyak** [dankogai/js-base64#93]
Hello,

At our Angular project we are using [`node-sass`](https://www.npmjs.com/package/node-sass) package for compiling files from `.scss` to normal `.css` file. [`Node-sass`](https://www.npmjs.com/package/node-sass) has some other dependencies and in one of them is included [`js-base64`](https://www.npmjs.com/package/js-base64) packge.

On the project, we also run WhiteSource scan during the builds, and it displays an alert - "Security Vulnerability" because of using an old version of the `jquery` library inside `js-base64/test/index.html` file and as a solution to fix this problem it proposes to upgrade `jquery` version from `2.1.4` to `3.4.0`. See at the attached screenshot. 
![image](https://user-images.githubusercontent.com/25721775/58186972-8c3dc680-7cbe-11e9-98b1-60166f84ff24.png).

So, could you please upgrade `jquery` version to `3.4.0` inside `js-base64/test/index.html` file?

**Comment by sv3k** [comment]
We have the same warning on all the angular projects. Adding the `./test` folder to `.npmignore` looks like an easy fix. Plus, having millions of weekly downloads for this lib, it could save gigabytes of traffic.

**Comment by dankogai** [comment]
@Sprokopyak Fixed in https://github.com/dankogai/js-base64/commit/cf8fc4a103de9707406e3bbb027797e6edba5f0e

@sv3k adding `./test` to `.npmignore' breaks `npm test` so I consider that too much.
