### ISSUE TITLE
Error while building js-base64

### ISSUE THREAD

**Issue by mgara** [dankogai/js-base64#95]
Uncaught SyntaxError: Invalid regular expression: /[Ã€-ÃŸ][Â€-Â¿]|[Ã -Ã¯][Â€-Â¿]{2}|[Ã°-Ã·][Â€-Â¿]{3}/: Range out of order in character class
Chrome : 74.0.3729
"js-base64": "^2.5.1",

"@vue/cli-plugin-babel": "^3.5.5",
    "@vue/cli-plugin-eslint": "^3.4.0",
    "@vue/cli-plugin-unit-jest": "^3.8.0",
    "@vue/cli-service": "^3.6.0",
    "@vue/eslint-config-airbnb": "^4.0.0",
    "@vue/test-utils": "1.0.0-beta.29",
    "babel-core": "7.0.0-bridge.0",
    "babel-eslint": "^10.0.1",
    "babel-jest": "^23.6.0",
    "eslint": "^5.16.0",
    "eslint-loader": "^2.1.2",
    "eslint-plugin-vue": "^5.2.2",
    "moment-locales-webpack-plugin": "^1.0.7",
    "node-sass": "^4.12.0",
    "prettier": "^1.17.0",
    "sass": "^1.18.0",
    "sass-loader": "^7.1.0",
    "vue-template-compiler": "^2.6.10",
    "webpack": "^4.32.0"

Build code :     "staging": "vue-cli-service build --mode staging --dest dist --target app",
It looks like during minification process the regex gets weird encoding ... so that the browser won't understand it ...

[Ã€-ÃŸ][Â€-Â¿]|[Ã -Ã¯][Â€-Â¿]{2}|[Ã°-Ã·][Â€-Â¿]{3} 
instead of  : 
    var re_btou = new RegExp([
        '[\xC0-\xDF][\x80-\xBF]',
        '[\xE0-\xEF][\x80-\xBF]{2}',
        '[\xF0-\xF7][\x80-\xBF]{3}'
    ].join('|'), 'g');

**Comment by mgara** [comment]
It works when I build on Windows
but when I build on centos .. it won't

**Comment by mgara** [comment]
Fixed by forcing the file encoding on nginx to utf-8

**Comment by dankogai** [comment]
I ought to have closed this.  I am doing so now…
