### ISSUE TITLE
You can decode ","

### ISSUE THREAD

**Issue by alien-neko** [dankogai/js-base64#98]
Just a demo. I have a str = 'MjAxOTA5MzAlMkMwLTAlMkMwLTAlMkMwLTA=', i will get a strange result = '20190930%2C0-0%2C0-0%2C0-0'

**Comment by dankogai** [comment]
What's wrong with it? they all return `20190930%2C0-0%2C0-0%2C0-0`

* `Base64.decode(str)`
* `atob(str)` // of browser built-in
* `/usr/bin/base64 -D` # of MacOS
