### ISSUE TITLE
Require.js trigger error

### ISSUE THREAD

**Issue by aizuyan** [dankogai/js-base64#99]
when i using [require.js](https://requirejs.org/)

trigger error in the fellow:
```js
    if (typeof module !== 'undefined' && module.exports) {
        try {
            buffer = require('buffer').Buffer;
        } catch (err) {
            buffer = undefined;
        }
    }
```

```
require.js:168 Uncaught Error: Script error for "buffer", needed by: base64
```

require.js will regex match dependencies fist，so loaded `buffer` trigger error

**Comment by dankogai** [comment]
`buffer` is no longer used.
https://github.com/dankogai/js-base64/commit/0df4bd24c08fc6143577b0fac7aa5a323eb52660
